version: "3.8"
services:
  mongodb_container:
    ports:
      - "27017:27017"
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/admin
    depends_on:
      - mongodb
    logging:
      options:
        max-size: 1g
    volumes:
      - mongodb_data_container:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080

volumes:
  mongodb_data_container: