version: '3.8'
services:
  mongo:
    ports:
      - '27017:27017'
    image: mongo
    container_name: mongodb
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_example
    volumes:
#        - ./src/web/config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - my_volume:/path/in/container
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root_example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: user_example
  web:
    image: demo-node-app
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://root:root_example@mongo:27017/admin
volumes:
  my_volume: