version: '3'
services:
  postgres-db:
    image: "postgres:12"
    container_name: "node-gmp-db"
    environment:
      - POSTGRES_USER=node_gmp
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=node_gmp
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: